config/routes.rb
Rails.application.routes.draw do
  resources :garments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garment.rb
class Garment < ApplicationRecord
  has_attached_file :image
  do_not_validate_attachment_file_type :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/garments_controller.rb
class GarmentsController < ApplicationController
  before_action :set_garment, only: [:show, :edit, :update, :destroy]

  # GET /garments
  # GET /garments.json
  def index
    @garments = Garment.all
  end

  # GET /garments/1
  # GET /garments/1.json
  def show
  end

  # GET /garments/new
  def new
    @garment = Garment.new
  end

  # GET /garments/1/edit
  def edit
  end

  # POST /garments
  # POST /garments.json
  def create
    @garment = Garment.new(garment_params)

    respond_to do |format|
      if @garment.save
        format.html { redirect_to @garment, notice: 'Garment was successfully created.' }
        format.json { render :show, status: :created, location: @garment }
      else
        format.html { render :new }
        format.json { render json: @garment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /garments/1
  # PATCH/PUT /garments/1.json
  def update
    respond_to do |format|
      if @garment.update(garment_params)
        format.html { redirect_to @garment, notice: 'Garment was successfully updated.' }
        format.json { render :show, status: :ok, location: @garment }
      else
        format.html { render :edit }
        format.json { render json: @garment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /garments/1
  # DELETE /garments/1.json
  def destroy
    @garment.destroy
    respond_to do |format|
      format.html { redirect_to garments_url, notice: 'Garment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garment
      @garment = Garment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def garment_params
      params.require(:garment).permit(:sort, :length, :notes, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/garments_helper.rb
module GarmentsHelper
end

app/views/garments/_form.html.erb
<%= form_with(model: garment, local: true) do |form| %>
  <% if garment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(garment.errors.count, "error") %> prohibited this garment from being saved:</h2>

      <ul>
      <% garment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type %>
    <%= form.text_field :sort, id: :garment_sort %>
  </div>


  <div class="field">
    <%= form.label :length %>
    <%= form.text_field :length, id: :garment_length %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :garment_notes %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :garment_image, :required => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/garments/edit.html.erb
<h1>Editing Garment</h1>

<%= render 'form', garment: @garment %>

<%= link_to 'Show', @garment %> |
<%= link_to 'Back', garments_path %>

app/views/garments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Garments</h1>

<table>
  <thead>
    <tr>
      <th>Sort</th>
      <th>Length</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @garments.any? %>
      <% @garments.each do |garment| %>
        <tr>
          <td><%= link_to image_tag(garment.image.url, id: :garment_image), garment.image.url, target: '_blank' %></dt>
          <td><%= garment.sort %></td>
          <td><%= garment.length %></td>
          <td><%= garment.notes %></td>
          <td><%= link_to 'Show', garment %></td>
          <td><%= link_to 'Edit', edit_garment_path(garment) %></td>
          <td><%= link_to 'Destroy', garment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% else %>
      No garments yet
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Garment', new_garment_path %>

app/views/garments/new.html.erb
<h1>New Garment</h1>

<%= render 'form', garment: @garment %>

<%= link_to 'Back', garments_path %>

app/views/garments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @garment.sort %>
  <%= link_to image_tag(@garment.image.url, id: :garment_image), @garment.image.url, target: '_blank' %>
</p>

<p>
  <strong>Length:</strong>
  <%= @garment.length %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @garment.notes %>
</p>

<%= link_to 'Edit', edit_garment_path(@garment) %> |
<%= link_to 'Back', garments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webdrobe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>